export const COPY_ABSOLUTE_REFERENCE_COMMAND = 'copyFilePathWithLineNumbers.copyAbsoluteReference';
export const COPY_RELATIVE_REFERENCE_COMMAND = 'copyFilePathWithLineNumbers.copyRelativeReference';
